[package]
name = "sbuild"
version = "0.2.0"
license = "MIT"
edition = "2021"
description = "Tooling for the soarpkgs package format"
repository = "https://github.com/pkgforge/sbuilder"
keywords = ["soar", "sbuild", "package", "metadata"]

[dependencies]
blake3 = "1.8.5"
clap = { version = "4", features = ["derive", "env"] }
colored = "3.1"
futures = "0.3"
glob = "0.3"
indexmap = "2.13"
regex = "1"
reqwest = { version = "0.13", default-features = false, features = ["http2", "json", "rustls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
tempfile = "3.27.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = "1.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
